version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
      MYSQL_PASSWORD: '!ChangeMe!'
      MYSQL_USER: 'db_user'
      MYSQL_DATABASE: 'subscription'
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  network:
    external: false